import { Entity, OneToMany, PrimaryKey, Property } from '@mikro-orm/core';
import { Field, Int, ObjectType } from 'type-graphql';
import Consultation from './consultation';

@ObjectType()
@Entity()
export default class Doctor {

  @Field(() => Int)
  @PrimaryKey()
  id: number;

  @Field(() => String)
  @Property()
  firstName: string;

  @Field(() => String)
  @Property()
  lastName: string;

  @Field(() => String)
  @Property()
  email: string;
  
  // No field decorator here as we don't want to expose the password.
  @Property()
  password: string;

  @Field(() => String) 
  @Property({default: 'en_GB'}) // add default language as english. Need to discuss with FE team and decide on convention
  language: string;
  
  @Field(() => String)
  @Property({default: '00000'}) // have autogenerated code tbc.
  docPublicCode: string;

  @Field(() => [Consultation])
  @OneToMany(() => Consultation, consultation => consultation.doctorId)
  consultations: Consultation[];

}